version: '3.7'
services:
  openpose:
    build:
      context: ./openpose
      labels:
        - joram87/openpose-cpu:latest
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./openpose/models:/openpose/models
      - ./openpose/entrypoint.sh:/entrypoint.sh

  pifuhd:
    build:
      context: ./pifuhd
      labels:
        - joram87/pifuhd:latest
    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./pifuhd/models:/pifuhd/models
      - ./pifuhd/entrypoint.sh:/entrypoint.sh

  openmvs:
    build:
      context: ./openMVS
      labels:
        - joram87/openMVS:latest
    volumes:
      - ./input/caitlin_head:/data/input
      - ./openMVS/work:/data/work
      - ./openMVS/entrypoint.sh:/entrypoint.sh
